version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fraud-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Allows live-reloading without rebuilding the container
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: fraud-frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8000/predict
    depends_on:
      - api
